const test = require("node:test");
const assert = require("node:assert/strict");
const { assessBlmLayerMetadata, buildActiveClaimsQuery, sanitizeActiveClaimsGeoJson, validateResearchBounds } = require("../dist/blm.js");
const { createResearchSnapshot, parseResearchSnapshots, upsertResearchSnapshot } = require("../dist/research.js");
const { createClaimDraft, parseClaimDraft } = require("../dist/claim-draft.js");
const { arizonaWorkflow, californiaWorkflow, nevadaWorkflow, parseWorkflowProgress } = require("../dist/state-workflows.js");
const { addFieldObservation, createFieldEvidenceExport, createFieldObservation, describeGpsQuality, parseFieldObservations, serializeFieldEvidence } = require("../dist/field-record.js");
const { createTrackedDeadline, daysUntilDeadline, deadlineStatus, parseTrackedDeadlines } = require("../dist/deadline.js");
const { parseNevadaPacket, reviewNevadaPacket } = require("../dist/document-packet.js");
const { webSecurityHeaders } = require("../dist/security.js");
const { claimGridLocalRecords, collectLocalRecords, createLocalDataExport, parseLocalDataExport } = require("../dist/local-data.js");
test("accepts a bounded US viewport", () => assert.equal(validateResearchBounds({ west: -120, south: 38, east: -119, north: 39 }).ok, true));
test("rejects an oversized request", () => assert.match(validateResearchBounds({ west: -125, south: 30, east: -110, north: 40 }).error, /five degrees/i));
test("builds a constrained GeoJSON query", () => { const url = buildActiveClaimsQuery({ west: -120, south: 38, east: -119, north: 39 }); assert.equal(url.searchParams.get("f"), "geojson"); assert.equal(url.searchParams.get("resultRecordCount"), "1000"); assert.match(url.searchParams.get("outFields"), /QLTY/); });
test("creates an explicitly screening-only research snapshot", () => { const snapshot = createResearchSnapshot({ label: "Test Area", bounds: { west: -120, south: 38, east: -119, north: 39 }, activeClaimCount: 12, sourceCheckedAt: "2026-09-13T17:00:00.000Z" }, new Date("2026-09-13T18:00:00.000Z")); assert.equal(snapshot.screeningOnly, true); assert.equal(snapshot.savedAt, "2026-09-13T18:00:00.000Z"); });
test("ignores malformed persisted research data", () => assert.deepEqual(parseResearchSnapshots("not json"), []));
test("updates matching areas instead of duplicating them", () => { const snapshot = createResearchSnapshot({ label: "Test", bounds: { west: -120, south: 38, east: -119, north: 39 }, activeClaimCount: 1, sourceCheckedAt: "2026-09-13T17:00:00.000Z" }); assert.equal(upsertResearchSnapshot([snapshot], { ...snapshot, activeClaimCount: 2 }).length, 1); });
test("keeps research drafts separate from legal location", () => { const draft = createClaimDraft({ name: "  North wash ", state: "NV", county: "", claimType: "placer", stage: "research" }, new Date("2026-09-13T18:00:00.000Z")); assert.equal(draft.name, "North wash"); assert.equal(draft.locationDate, null); assert.equal(draft.federalRecordingDeadline, null); });
test("calculates the federal recording target from physical location", () => { const draft = createClaimDraft({ name: "North wash", state: "NV", county: "Nye", claimType: "placer", stage: "located", locationDate: "2026-09-01" }, new Date("2026-09-13T18:00:00.000Z")); assert.equal(draft.federalRecordingDeadline, "2026-11-30"); });
test("rejects future physical location dates", () => assert.throws(() => createClaimDraft({ name: "Test", state: "NV", county: "", claimType: "lode", stage: "located", locationDate: "2026-09-14" }, new Date("2026-09-13T18:00:00.000Z")), /future/i));
test("ignores malformed persisted claim drafts", () => assert.equal(parseClaimDraft('{"version":1}'), null));
test("Nevada workflow keeps authoritative source review dates", () => { assert.equal(nevadaWorkflow.state, "NV"); assert.ok(nevadaWorkflow.sources.every(source => source.checkedAt === "2026-09-13")); assert.match(nevadaWorkflow.notice, /does not determine/i); });
test("workflow progress accepts only known unique step identifiers", () => assert.deepEqual(parseWorkflowProgress('["records","fake","records","county"]', nevadaWorkflow.steps.map(step => step.id)), ["records", "county"]));
test("workflow progress safely rejects malformed storage", () => assert.deepEqual(parseWorkflowProgress("bad json", ["records"]), []));
test("creates an explicitly device-only field observation", () => { const record = createFieldObservation({ kind: "monument", note: "  Existing post  ", latitude: 38.9, longitude: -119.7, horizontalAccuracyMeters: 7, capturedAt: "2026-09-14T01:00:00.000Z", photoUri: " file:///photo.jpg " }, "field-test"); assert.equal(record.note, "Existing post"); assert.equal(record.photoUri, "file:///photo.jpg"); assert.equal(record.deviceReadingOnly, true); assert.equal(record.id, "field-test"); });
test("rejects impossible field coordinates", () => assert.throws(() => createFieldObservation({ kind: "site", latitude: 100, longitude: -119 }), /latitude/i));
test("classifies GPS readings without overstating precision", () => { assert.equal(describeGpsQuality(8), "strong"); assert.equal(describeGpsQuality(24), "moderate"); assert.equal(describeGpsQuality(80), "weak"); assert.equal(describeGpsQuality(null), "unknown"); });
test("rejects corrupted and non-evidence field storage", () => { assert.deepEqual(parseFieldObservations("broken"), []); assert.deepEqual(parseFieldObservations('[{"id":"fake","latitude":38,"longitude":-119,"capturedAt":"2026-09-14T01:00:00Z"}]'), []); });
test("deduplicates field records and keeps newest first", () => { const old = createFieldObservation({ kind: "site", latitude: 38, longitude: -119 }, "same"); const replacement = { ...old, note: "updated" }; assert.deepEqual(addFieldObservation([old], replacement), [replacement]); });
test("exports versioned field evidence with its safety caveat", () => { const record = createFieldObservation({ kind: "access", latitude: 38, longitude: -119, capturedAt: "2026-09-14T01:00:00Z" }, "export-me"); const packet = createFieldEvidenceExport([record], new Date("2026-09-14T07:00:00Z")); assert.equal(packet.schema, "claimgrid-field-evidence-v1"); assert.match(packet.caveat, /not a legal survey/i); assert.equal(packet.observations[0].deviceReadingOnly, true); assert.deepEqual(JSON.parse(serializeFieldEvidence([record], new Date("2026-09-14T07:00:00Z"))), packet); });
test("classifies filing deadlines by urgency", () => { const today = new Date("2026-09-14T12:00:00Z"); assert.equal(daysUntilDeadline("2026-09-20", today), 6); assert.equal(deadlineStatus("2026-09-13", today), "overdue"); assert.equal(deadlineStatus("2026-09-20", today), "urgent"); assert.equal(deadlineStatus("2026-10-14", today), "upcoming"); });
test("requires recorder verification for county deadlines", () => assert.throws(() => createTrackedDeadline({ kind: "county", label: "County recording", dueDate: "2026-09-30", authority: "Nye County Recorder", sourceUrl: "https://example.gov", verifiedAt: "2026-09-14", manuallyVerified: false }), /confirmed/i));
test("rejects unverified county deadlines from storage", () => assert.deepEqual(parseTrackedDeadlines('[{"id":"county-x","kind":"county","dueDate":"2026-09-30","sourceUrl":"https://example.gov","manuallyVerified":false}]'), []));
test("never represents a complete packet worksheet as ready to file", () => { const review = reviewNevadaPacket({ claimName:"North Wash",claimType:"placer",locatorNames:"Test Locator",mailingAddress:"1 Main St",county:"Nye",locationDate:"2026-09-01",landDescription:"T1N R2E Sec 3",mapHasNorthArrow:true,mapHasScale:true,mapHasClaimBoundaries:true,mapMatchesDescription:true }); assert.equal(review.status,"agency-review-required"); assert.equal(review.completed,review.total); assert.match(review.warnings.join(" "),/does not generate/i); });
test("identifies missing packet and map elements", () => { const review=reviewNevadaPacket({claimName:"",claimType:"placer",locatorNames:"",mailingAddress:"",county:"Nye",locationDate:"",landDescription:"",mapHasNorthArrow:false,mapHasScale:false,mapHasClaimBoundaries:false,mapMatchesDescription:false}); assert.equal(review.status,"incomplete"); assert.ok(review.missing.includes("Map north arrow")); });
test("safely rejects malformed packet drafts", () => assert.equal(parseNevadaPacket('{"claimName":1}'),null));
test("defines each production security header once", () => { const names=webSecurityHeaders.map(header=>header.key.toLowerCase()); assert.equal(new Set(names).size,names.length); assert.ok(names.includes("content-security-policy")); assert.ok(names.includes("strict-transport-security")); });
test("prevents framing and insecure active content", () => { const csp=webSecurityHeaders.find(header=>header.key==="Content-Security-Policy").value; assert.match(csp,/frame-ancestors 'none'/); assert.match(csp,/object-src 'none'/); assert.match(csp,/upgrade-insecure-requests/); });
test("denies unused sensitive browser capabilities", () => { const policy=webSecurityHeaders.find(header=>header.key==="Permissions-Policy").value; assert.match(policy,/camera=\(\)/); assert.match(policy,/geolocation=\(\)/); assert.match(policy,/microphone=\(\)/); assert.match(policy,/payment=\(\)/); });

test("collects only known ClaimGrid browser records", () => { const values={ "claimgrid:research:v1":"[]", "unrelated.secret":"nope" }; const found=collectLocalRecords(key=>values[key]??null); assert.equal(found.length,1); assert.equal(found[0].key,"claimgrid:research:v1"); });
test("creates a versioned exact-value local data export", () => { const records=[{ key:"claimgrid.claim-draft.v1",label:"Claim project draft",value:"{\\\"name\\\":\\\"Test\\\"}" }]; const packet=createLocalDataExport(records,new Date("2026-09-14T15:00:00Z")); assert.equal(packet.schema,"claimgrid-local-data-v1"); assert.equal(packet.exportedAt,"2026-09-14T15:00:00.000Z"); assert.deepEqual(packet.records,records); });
test("keeps a unique registry for every browser record type", () => { const keys=claimGridLocalRecords.map(record=>record.key); assert.equal(new Set(keys).size,keys.length); assert.ok(keys.every(key=>key.startsWith("claimgrid"))); });

test("Arizona workflow separates State Trust Land from federal claims", () => { assert.equal(arizonaWorkflow.state,"AZ"); assert.match(arizonaWorkflow.notice,/State Trust Land/i); assert.ok(arizonaWorkflow.steps.some(step=>/State Trust Land/i.test(step.title))); });
test("Arizona workflow uses freshly reviewed authoritative sources", () => { assert.ok(arizonaWorkflow.sources.every(source=>source.checkedAt==="2026-09-14")); assert.ok(arizonaWorkflow.sources.some(source=>source.authority==="Arizona Legislature")); assert.ok(arizonaWorkflow.sources.every(source=>source.url.startsWith("https://"))); });
test("Arizona progress rejects Nevada and unknown gate identifiers", () => { const ids=arizonaWorkflow.steps.map(step=>step.id); assert.deepEqual(parseWorkflowProgress('["az-records","records","fake","az-records"]',ids),["az-records"]); });

test("sanitizes a valid BLM claim feature and strips unknown properties", () => { const result=sanitizeActiveClaimsGeoJson({type:"FeatureCollection",features:[{type:"Feature",id:7,properties:{CSE_NAME:"Test",SECRET:"drop"},geometry:{type:"Polygon",coordinates:[[[-120,38],[-119,38],[-119,39],[-120,38]]]}}]}); assert.equal(result.ok,true); assert.deepEqual(result.collection.features[0].properties,{CSE_NAME:"Test"}); });
test("rejects malformed or out-of-range BLM geometry", () => { const result=sanitizeActiveClaimsGeoJson({type:"FeatureCollection",features:[{type:"Feature",properties:{},geometry:{type:"Polygon",coordinates:[[[-220,38],[-119,38],[-119,39],[-220,38]]]}}]}); assert.equal(result.ok,false); assert.match(result.error,/coordinates/i); });
test("rejects unsupported upstream geometry types", () => { const result=sanitizeActiveClaimsGeoJson({type:"FeatureCollection",features:[{type:"Feature",properties:{},geometry:{type:"Point",coordinates:[-120,38]}}]}); assert.equal(result.ok,false); assert.match(result.error,/unsupported geometry/i); });
test("rejects upstream feature counts above the public result cap", () => { const result=sanitizeActiveClaimsGeoJson({type:"FeatureCollection",features:Array.from({length:1001},()=>({}))}); assert.equal(result.ok,false); assert.match(result.error,/feature safety limit/i); });

test("restores only known unique ClaimGrid backup records", () => { const raw=JSON.stringify({schema:"claimgrid-local-data-v1",storage:"browser-local",records:[{key:"claimgrid.claim-draft.v1",label:"spoofed",description:"spoofed",value:"{}"}]}); const result=parseLocalDataExport(raw); assert.equal(result.ok,true); assert.equal(result.records[0].label,"Claim project draft"); });
test("rejects unknown and duplicate backup storage keys", () => { const base={schema:"claimgrid-local-data-v1",storage:"browser-local"}; assert.equal(parseLocalDataExport(JSON.stringify({...base,records:[{key:"other.key",value:"{}"}]})).ok,false); const duplicate={key:"claimgrid.claim-draft.v1",value:"{}"}; assert.equal(parseLocalDataExport(JSON.stringify({...base,records:[duplicate,duplicate]})).ok,false); });
test("rejects malformed and oversized local backups", () => { assert.match(parseLocalDataExport("not json").error,/valid JSON/i); const large=JSON.stringify({schema:"claimgrid-local-data-v1",storage:"browser-local",records:[{key:"claimgrid.claim-draft.v1",value:"x".repeat(1000001)}]}); assert.match(parseLocalDataExport(large).error,/1 MB/i); });

test("accepts compatible BLM layer metadata", () => { const result=assessBlmLayerMetadata({name:"Active Mining Claims",currentVersion:11.5,type:"Feature Layer",geometryType:"esriGeometryPolygon",capabilities:"Map,Query,Data",fields:["OBJECTID","CSE_NR","CSE_NAME","CSE_DISP","BLM_PROD","QLTY","RCRD_ACRS","GEO_STATE"].map(name=>({name}))}); assert.equal(result.compatible,true); assert.equal(result.layerName,"Active Mining Claims"); });
test("detects a breaking BLM layer schema change", () => { const value={name:"Active Mining Claims",currentVersion:11.5,type:"Feature Layer",geometryType:"esriGeometryPolygon",capabilities:"Map,Query,Data",fields:["OBJECTID","CSE_NR","CSE_NAME","CSE_DISP","BLM_PROD","QLTY","RCRD_ACRS","GEO_STATE"].map(name=>({name}))}; value.geometryType="esriGeometryPoint"; value.capabilities="Map"; value.fields=value.fields.filter(field=>field.name!=="CSE_NR"); const result=assessBlmLayerMetadata(value); assert.equal(result.compatible,false); assert.match(result.issues.join(" "),/polygon geometry/i); assert.match(result.issues.join(" "),/Query capability/i); assert.match(result.issues.join(" "),/CSE_NR/); });
test("preserves an official upstream edit timestamp when provided", () => { const value={name:"Active Mining Claims",currentVersion:11.5,type:"Feature Layer",geometryType:"esriGeometryPolygon",capabilities:"Map,Query,Data",fields:["OBJECTID","CSE_NR","CSE_NAME","CSE_DISP","BLM_PROD","QLTY","RCRD_ACRS","GEO_STATE"].map(name=>({name}))}; value.editingInfo={lastEditDate:1789344000000}; const result=assessBlmLayerMetadata(value); assert.equal(result.upstreamLastEditedAt,"2026-09-14T00:00:00.000Z"); });


test("California workflow preserves land-status and surface-use gates", () => { assert.equal(californiaWorkflow.state,"CA"); assert.match(californiaWorkflow.notice,/Federal ownership alone/i); assert.ok(californiaWorkflow.steps.some(step=>/surface-use/i.test(step.title))); });
test("California workflow uses current authoritative sources", () => { assert.ok(californiaWorkflow.sources.every(source=>source.checkedAt==="2026-09-14")); assert.ok(californiaWorkflow.sources.some(source=>source.authority==="California Legislature")); assert.ok(californiaWorkflow.sources.every(source=>source.url.startsWith("https://"))); });
test("California progress rejects other-state and unknown gates", () => { const ids=californiaWorkflow.steps.map(step=>step.id); assert.deepEqual(parseWorkflowProgress('["ca-status","az-records","fake","ca-status"]',ids),["ca-status"]); });
