import { NextRequest, NextResponse } from "next/server";
import { BLM_CLOSED_CLAIMS_LAYER, buildClosedClaimsQuery, createSafeServerErrorEvent, sanitizeClosedClaimsResponse, validateResearchBounds } from "@claimgrid/core";
export const runtime = "nodejs";
export async function GET(request: NextRequest) {
  const params=request.nextUrl.searchParams; const validation=validateResearchBounds({west:params.get("west")??"",south:params.get("south")??"",east:params.get("east")??"",north:params.get("north")??""});
  if(!validation.ok) return NextResponse.json({error:validation.error},{status:400});
  try { const response=await fetch(buildClosedClaimsQuery(validation.bounds),{headers:{Accept:"application/json"},cache:"no-store",signal:AbortSignal.timeout(12_000)}); if(!response.ok){const error=new Error();error.name="BlmClosedClaimsHttpError";throw error;} const summary=sanitizeClosedClaimsResponse(await response.json()); if(!summary){const error=new Error();error.name="BlmClosedClaimsPayloadError";throw error;} return NextResponse.json({...summary,metadata:{source:"U.S. Bureau of Land Management — MLRS Closed Mining Claims",sourceUrl:BLM_CLOSED_CLAIMS_LAYER,retrievedAt:new Date().toISOString(),screeningOnly:true,warning:"Closed claims are historical screening evidence only. Closure does not prove land reopened, establish present mineral-entry status, resolve prior rights or monuments, or establish availability. Verify the current MLRS case file, land status, legal description, withdrawals, and conditions on the ground."}},{headers:{"Cache-Control":"public, s-maxage=900, stale-while-revalidate=3600"}}); }
  catch(error){console.error(JSON.stringify(createSafeServerErrorEvent({error,method:"GET",route:"/api/blm/closed-claims",routeType:"route",release:process.env.VERCEL_GIT_COMMIT_SHA})));return NextResponse.json({error:"The official BLM closed-claims layer is temporarily unavailable. No historical or land-status conclusion can be drawn."},{status:502});}
}
