"use client";
import { useEffect,useState } from "react";
import { parseClaimDraft,parseFederalPacket,reviewFederalPacket,type FederalPacketDraft } from "@claimgrid/core";
const KEY="claimgrid.packet.blm.v1";
const empty:FederalPacketDraft={claimName:"",claimType:"placer",locatorNames:"",mailingAddress:"",state:"NV",county:"",locationDate:"",acreage:"",landDescription:"",countyDocumentNumber:"",countyCopyReady:false,mapAttached:false,mapMatchesLocation:false,currentFeesChecked:false};
export default function BlmPacket(){
  const [draft,setDraft]=useState(empty),[saved,setSaved]=useState(false);
  useEffect(()=>{const stored=parseFederalPacket(localStorage.getItem(KEY));if(stored){setDraft(stored);return}const project=parseClaimDraft(localStorage.getItem("claimgrid.claim-draft.v1"));if(project)setDraft(current=>({...current,claimName:project.name,claimType:project.claimType,state:project.state,county:project.county,locationDate:project.locationDate??""}))},[]);
  const review=reviewFederalPacket(draft);
  function text(key:keyof FederalPacketDraft,value:string){setDraft(current=>({...current,[key]:value}));setSaved(false)}
  function check(key:keyof FederalPacketDraft,value:boolean){setDraft(current=>({...current,[key]:value}));setSaved(false)}
  function save(){localStorage.setItem(KEY,JSON.stringify(draft));setSaved(true)}
  return <main className="packetPage"><nav><a href="/" className="packetBrand"><span>CG</span>ClaimGrid</a><div><a href="/claim/new">Project</a><a href="/deadlines">Deadlines</a></div></nav><div className="packetShell"><header><span>BLM PREPARATION WORKSHEET · SOURCE CHECKED 2026-09-21</span><h1>Cross-check the federal recording packet.</h1><p>Organize the information described in current BLM recording guidance. This browser-local worksheet is not an official form, does not file anything, and cannot establish validity or land availability.</p></header><div className="packetLayout"><form onSubmit={event=>{event.preventDefault();save()}}>
    <div className="packetTwo"><label>Claim or site name<input maxLength={200} value={draft.claimName} onChange={e=>text("claimName",e.target.value)} required/></label><label>Claim or site type<select value={draft.claimType} onChange={e=>text("claimType",e.target.value)}><option value="placer">Placer</option><option value="lode">Lode</option><option value="mill">Mill site</option><option value="tunnel">Tunnel site</option></select></label></div>
    <label>All claimant names<textarea maxLength={4000} value={draft.locatorNames} onChange={e=>text("locatorNames",e.target.value)} placeholder="Match the recorded county document" required/></label><label>Current mailing address for every claimant<textarea maxLength={4000} value={draft.mailingAddress} onChange={e=>text("mailingAddress",e.target.value)} required/></label>
    <div className="packetTwo"><label>State code<input maxLength={2} value={draft.state} onChange={e=>text("state",e.target.value.toUpperCase())} required/></label><label>County or borough<input maxLength={200} value={draft.county} onChange={e=>text("county",e.target.value)} required/></label></div>
    <div className="packetTwo"><label>Physical location date<input type="date" value={draft.locationDate} onChange={e=>text("locationDate",e.target.value)} required/></label><label>Claimed acreage<input type="number" min="0.01" max="10000" step="0.01" value={draft.acreage} onChange={e=>text("acreage",e.target.value)} required/></label></div>
    <label>Legal land description<textarea maxLength={4000} value={draft.landDescription} onChange={e=>text("landDescription",e.target.value)} placeholder="State, meridian, township, range, section and aliquot part—or another accepted description" required/></label><label>County recording document number or reference<input maxLength={200} value={draft.countyDocumentNumber} onChange={e=>text("countyDocumentNumber",e.target.value)} required/></label>
    <fieldset><legend>BLM packet cross-check</legend>{[["countyCopyReady","Recorded county notice copy is ready"],["mapAttached","Claim-boundary map is attached"],["mapMatchesLocation","Map, notice, legal description, and physical location agree"],["currentFeesChecked","Current BLM fees were checked directly before filing"]].map(([key,label])=><label className="packetCheck" key={key}><input type="checkbox" checked={draft[key as keyof FederalPacketDraft] as boolean} onChange={e=>check(key as keyof FederalPacketDraft,e.target.checked)}/><span>{label}</span></label>)}</fieldset>
    <button className="packetSave">Save private worksheet</button>{saved&&<p className="packetSaved" role="status">Saved in this browser.</p>}
  </form><aside><div className={`packetScore ${review.status}`}><span>{review.completed} / {review.total}</span><h2>{review.status==="incomplete"?"Information still missing":"Agency review required"}</h2><p>{review.status==="incomplete"?"Complete the worksheet, then verify every item against current county and BLM instructions.":"Every worksheet field is present. This does not mean the packet is legally sufficient or ready to file."}</p></div>{review.missing.length>0&&<><h3>Missing cross-checks</h3><ul>{review.missing.map(item=><li key={item}>{item}</li>)}</ul></>}<div className="packetWarning"><b>Mandatory final checks</b>{review.warnings.map(warning=><p key={warning}>{warning}</p>)}</div><a className="packetSource" href="https://www.blm.gov/programs/energy-and-minerals/mining-and-minerals/locatable-minerals/mining-claims/recording" target="_blank" rel="noreferrer">Open current BLM recording guidance ↗</a><a className="packetSource" href="https://mlrs.blm.gov/" target="_blank" rel="noreferrer">Open MLRS ↗</a></aside></div></div></main>
}
